[config]

[templates.ghostty-dark]
input_path = './matugen/templates/ghostty-colors-dark.conf'
output_path = '~/.config/ghostty/config-dankcolors'

[templates.ghostty-light]
input_path = './matugen/templates/ghostty-colors-light.conf'
output_path = '~/.config/ghostty/config-dankcolors'

[templates.dgop]
input_path = './matugen/templates/dgop.json'
output_path = '~/.config/dgop/colors.json'

[templates.fastfetch]
input_path = './matugen/templates/fastfetch-colors.jsonc'
output_path = '~/.config/fastfetch/colors.jsonc'